services:
    Codefog\InstagramBundle\Controller\InstagramController:
        public: true
        arguments:
            - "@database_connection"
            - "@router"
            - "@session"
            - "@security.token_storage"
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: contao }

    Codefog\InstagramBundle\EventListener\ModuleListener:
        public: true
        arguments:
            - "@router"
            - "@session"
